disabled = false
locale = "en"
label = "English"
weight = 2
title = "SHRMP0"

[params]
  displayName = "EN"
  isoCode = "en-US"
  rtl = false
  dateFormat = "January 2, 2006"
  logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Hi! This is my website where I post whatever I feel like... expect randomness."
  copyright = "2024–{ year } · [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"

[params.author]
  name = "SHRMP0"
#   email = "youremail@example.com"
  image = "img/author.en.png"
  imageQuality = 96
  headline = "Hi! This is my website where I post whatever I feel like... expect randomness. This isn't the only place where I hangout, you can also find me at:"
  bio = "The owner of da shrimp website"
  links = [
#     { email = "mailto:hello@your_domain.com" },
#     { link = "https://link-to-some-website.com/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
    { bluesky = "https://bsky.app/profile/shrmp0.com.br" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/SHRMP0" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
#     { itch-io = "https://username.itch.io" },
#     { keybase = "https://keybase.io/username" },
#     { keyoxide = "https://keyoxide.org/URI" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
#     { linkedin = "https://linkedin.com/in/username" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { matrix = "https://matrix.to/#/URI" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { signal = "https://signal.me/#eu/userid" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { spotify = "https://open.spotify.com/user/userid" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    { steam = "https://steamcommunity.com/id/shrmp0" },
#     { strava = "https://www.strava.com/athletes/username" },
#     { telegram = "https://t.me/username" },
#     { threads = "https://www.threads.net/@username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
    { twitch = "https://www.twitch.tv/shrmp0" },
#     { untappd = "https://untappd.com/user/username" },
#     { twitter = "https://twitter.com/username" },
#     { x-twitter = "https://twitter.com/username" },
#     { whatsapp = "https://wa.me/phone-number" },
    { youtube = "https://www.youtube.com/@SHRMP0" },
#     { ko-fi = "https://ko-fi.com/username" },
#     { codeberg = "https://codeberg.org/username"},
#     { printables = "https://www.printables.com/@username"},
  ]
