baseURL: "https://shrmp0.com.br/"
title: SHRMP0
copyright: "2024–2025 · [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
theme: PaperMod
enableEmoji: true
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

defaultContentLanguage: pt
defaultContentLanguageInSubdir: false
languages:
  pt:
    disabled: false
    languageCode: pt-BR
    languageDirection: ltr
    languageName: "Português"
    
  en:
    disabled: false
    languageCode: en-US
    languageDirection: ltr
    languageName: "English"
    
    params:
      description: "Hi! This is my website where I post whatever I feel like... expect randomness."
      DateFormat: "January 2, 2006"
      
      label:
        text: "Home"
      
      profileMode:
        subtitle: "Hi! This is my website where I post whatever I feel like... expect randomness. This isn't the only place where I hangout, you can also find me at:"
        imageTitle: "The capybara wearing Jason Voorhees' mask avatar from Age of Empires III: Definitive Edition."
        buttons:
          - name: Posts
            url: /en/posts/
          - name: Discover
            title: "Perhaps you'll learn something new..."
            url: https://en.wikipedia.org/wiki/Capybara
      
      homeInfoParams:
        Content: "Hi! This is my website where I post whatever I feel like... expect randomness. This isn't the only place where I hangout, you can also find me at:"
      
      editPost:
        Text: "Suggest changes"
      
    menus:
      main:
        - name: Archive
          url: /en/archives/
          weight: 10
        - name: Tags
          url: /en/tags/
          weight: 10
        - name: Search
          url: /en/search/
          weight: 20
        - name: "\U0001F480"
          title: "Do you have what it takes to click?"
          url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
          weight: 30
    weight: 1

pagination:
  disableAliases: true
  pagerSize: 5
  path: page

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: SHRMP0
  description: "Oi! Este é o meu site onde eu posto o que me der na telha... espere aleatoriedades."
  keywords: [Blog, Homepage, Personal]
  author: "SHRMP0" # ["Me", "You"] multiple authors
  images: ["/opengraph.png"] # link or path of image for opengraph, twitter-cards
  DateFormat: "2 de January de 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.png"
    favicon16x16: "/favicon16x16.png"
    favicon32x32: "/favicon32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"

  label:
    text: "Início"
    icon: "/apple-touch-icon.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "\U0001F364 SHRMP0 \U0001F990"
    subtitle: "Oi! Este é o meu site onde eu posto o que me der na telha... espere aleatoriedades. Aqui não é o único lugar que habito, você também pode me encontrar em:"
    imageUrl: "/images/capybara-aoe3de.png"
    imageWidth: 128
    imageHeight: 128
    imageTitle: "O famigerado avatar da capivara com máscara de Jason Voorhees do Age of Empires III: Definitive Edition."
    buttons:
      - name: Posts
        url: /posts/
      - name: Descubra
        title: "Quem sabe você não aprende algo novo..."
        url: "https://pt.wikipedia.org/wiki/Capivara"

  # home-info mode
  homeInfoParams:
    Title: "\U0001F364 SHRMP0 \U0001F990"
    Content: "Oi! Este é o meu site onde eu posto o que me der na telha... espere aleatoriedades. Aqui não é o único lugar que habito, você também pode me encontrar em:"

  social: true
  socialIcons:
    - name: bluesky
      title: Bluesky
      url: "https://bsky.app/profile/shrmp0.com.br"
    - name: github
      title: GitHub
      url: "https://github.com/SHRMP0"
    - name: linkedin
      title: LinkedIn
      url: "https://www.linkedin.com/in/davigazevedo/"
    - name: steam
      title: Steam
      url: "https://steamcommunity.com/id/shrmp0"
    - name: twitch
      title: Twitch
      url: "https://www.twitch.tv/shrmp0"
    - name: youtube
      title: YouTube
      url: "https://www.youtube.com/@SHRMP0"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page
    responsiveImages: true
    linkFullImages: false

  editPost:
    URL: "https://github.com/SHRMP0/SHRMP0.github.io/tree/main/content"
    Text: "Sugerir mudanças" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

menus:
  main:
    - name: Arquivo
      url: /archives/
      weight: 10
    - name: Tags
      url: /tags/
      weight: 10
    - name: Pesquisar
      url: /search/
      weight: 20
    - name: "\U0001F480"
      title: "Tem coragem de clicar?"
      url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
      weight: 30
weight: 1

services:
  googleAnalytics:
    id: "G-6K0J30SLLN"

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true

markup:
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai
